### PR TITLE
adding ERD for phenopacket v2.0.0

### LINKED ISSUE #2: Create ERD for Phenopackets v2 relational schema

### PR DESCRIPTION
**Pull request by yash-puligundla**
ERD for [phenopackets v2.0.0](https://phenopacket-schema.readthedocs.io/en/2.0.0/phenopacket.html)

**Notes:**
For ease of implementation, I made the following assumptions 
- VariantDescriptor -> Variation is set to be a string as opposed to a VRS object.
- protobuf type is replaced with string
- Didn't represent the either-or condition in the ERD (Example: call field in [GenomicInterpretation](https://phenopacket-schema.readthedocs.io/en/2.0.0/genomic-interpretation.html#rstgenomicinterpretation))
- At some places, a list of strings is replaced by just a string (Example: xrefs in [GeneDescriptor](https://phenopacket-schema.readthedocs.io/en/2.0.0/gene.html))
- categorical values are treated as strings
- ontology classes are sometimes added in as fields, unless they have a 0/1..* Multiplicity
- If there is no unique PK, set UUID as PK.

Please let me know if there is any feedback @jb-adams

### CODE REVIEW

**Comment by yash-puligundla** [comment]
Changes made:
- Added table cardinalities
- removed duplicate ontology tables

Outstanding Questions:
1. Does it make sense for the "Procedure" table to have multiple "body sites" or "performed" associated with a unique "code"?
2. Can one "ExternalReference" be associated with multiple "MetaData"?


@jb-adams  Ready for review. (I don't see an option to add you as a reviewer)

**Comment by jb-adams** [comment]
@yash-puligundla 

1. Can you write the link/instructions for loading the `.svg` and/or `.drawio` files?
2. Should we also get Jules and Peter to review?

**Comment by yash-puligundla** [comment]
> @yash-puligundla
> 
> 1. Can you write the link/instructions for loading the `.svg` and/or `.drawio` files?
> 2. Should we also get Jules and Peter to review?

Hi @jb-adams, I have added a link to the instructions in the README file. I will shoot an email to Jules and Peter for a review. Thank you!

**Comment by jb-adams** [comment]
This is amazing, great work @yash-puligundla !

I wonder if it would be better to put the many-to-many (pink arrow) relationships between ontology_class and another table on the other table, rather than on ontology_class. For example, on ontology_class, there's a field `fk_phenotypic_feature_modifier` that has a relationship with `phenotypic_feature` through a join table. Would it be better to put the pink arrow on the `phenotypic_feature` table instead of (or in addition to) having it on the `ontology_class` table? Just an idea!

**Comment by jb-adams** [comment]
I'm also wondering if time element-based relationships should be zero-or-one-to zero-or-one rather than zero-or-one-to-zero-or-many. Will there be instances where a single time element applies to multiple subjects, phenotypic features, etc? Or should each time element only correspond to one other entry?

**Comment by yash-puligundla** [comment]
> This is amazing, great work @yash-puligundla !
> 
> I wonder if it would be better to put the many-to-many (pink arrow) relationships between ontology_class and another table on the other table, rather than on ontology_class. For example, on ontology_class, there's a field `fk_phenotypic_feature_modifier` that has a relationship with `phenotypic_feature` through a join table. Would it be better to put the pink arrow on the `phenotypic_feature` table instead of (or in addition to) having it on the `ontology_class` table? Just an idea!

@jb-adams  I agree! This would make it more readable. I have added many-to-many (pink arrow) relationships on both tables. To avoid confusion, these arrows are dotted.

**Comment by yash-puligundla** [comment]
> I'm also wondering if time element-based relationships should be zero-or-one-to zero-or-one rather than zero-or-one-to-zero-or-many. Will there be instances where a single time element applies to multiple subjects, phenotypic features, etc? Or should each time element only correspond to one other entry?

I am a little confused here as well. My understanding is that though it is highly unlikely, there is still a chance or edge case that it could happen. For example, 2 different phenopackets might have their interpretation made at the exact same time. Let me know if you disagree with my assumption.

**Review by jb-adams — APPROVED** [review]
The ERD looks awesome, amazing work @yash-puligundla !

**Pull request merged**
